-- Reference production schema for the enterprise chatbot feature branch.
-- The local demo uses Hibernate ddl-auto=update with file-backed H2.

create table users (
    id bigint generated by default as identity primary key,
    username varchar(160) not null unique,
    created_at timestamp not null
);

create table chat_sessions (
    id varchar(36) primary key,
    user_key varchar(160) not null,
    title varchar(180) not null,
    private_mode boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table chat_messages (
    id bigint generated by default as identity primary key,
    session_id varchar(36) not null,
    role varchar(20) not null,
    content clob not null,
    created_at timestamp not null
);

create table chat_questions (
    id bigint generated by default as identity primary key,
    question varchar(500) not null,
    answer clob not null,
    keywords varchar(500) not null,
    normalized_question varchar(500),
    normalized_keywords varchar(500),
    created_at timestamp not null
);

create table chat_question_tokens (
    id bigint generated by default as identity primary key,
    question_id bigint not null,
    token varchar(80) not null,
    constraint uk_chat_question_tokens_question_token unique (question_id, token)
);

create table uploaded_documents (
    id bigint generated by default as identity primary key,
    session_id varchar(36),
    source_name varchar(260) not null,
    source_type varchar(40) not null,
    source_url varchar(600),
    media_type varchar(120),
    parser_name varchar(120),
    content_hash varchar(64),
    page_count integer,
    chunk_count integer,
    ingestion_status varchar(40),
    private_mode boolean not null,
    extracted_text clob not null,
    metadata_json clob,
    created_at timestamp not null
);

create table embeddings_metadata (
    id bigint generated by default as identity primary key,
    namespace varchar(80) not null,
    session_id varchar(36),
    document_id bigint,
    source_name varchar(260) not null,
    source_type varchar(40) not null,
    source_url varchar(600),
    page_number integer,
    section_title varchar(260),
    chunk_index integer,
    token_estimate integer,
    content_hash varchar(64),
    content_chunk clob not null,
    vector_json clob not null,
    metadata_json clob,
    private_mode boolean not null,
    created_at timestamp not null
);

create index idx_chat_sessions_user_updated on chat_sessions(user_key, updated_at);
create index idx_chat_messages_session_created on chat_messages(session_id, created_at);
create index idx_chat_questions_norm_question on chat_questions(normalized_question);
create index idx_chat_questions_norm_keywords on chat_questions(normalized_keywords);
create index idx_chat_question_tokens_token on chat_question_tokens(token);
create index idx_chat_question_tokens_question on chat_question_tokens(question_id);
create index idx_embeddings_private_created on embeddings_metadata(private_mode, created_at);
create index idx_embeddings_session_private on embeddings_metadata(session_id, private_mode);
create index idx_embeddings_document on embeddings_metadata(document_id);
create index idx_embeddings_hash on embeddings_metadata(content_hash);
